{{- if and (.Values.Agent.Enabled) -}}
apiVersion: v1
kind: List
items:
{{- $root := . -}}
{{- range $pkey, $pval := .Values.Agent.PodTemplates -}}
{{- range $ckey, $cval := $pval.Containers -}}
{{- if $cval.Build }}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
{{ include "jenkins-openshift.labels" $root | indent 6 }}
      build: jenkins
      image: {{ $ckey | lower | quote }}
    name: {{ regexSplit "/" $cval.Image -1 | last}}
  spec:
    failedBuildsHistoryLimit: 1
    successfulBuildsHistoryLimit: 1
    output:
      to:
        kind: ImageStreamTag
        name: "{{ regexSplit "/" $cval.Image -1 | last }}:{{ $cval.ImageTag }}"
    postCommit: {}
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1000m
        memory: 512Mi
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: {{ $cval.Build.Git.Uri | quote }}
        ref: {{ default "master" $cval.Build.Git.Ref | quote }}
      contextDir: {{ $cval.Build.ContextDir | quote }}
    strategy:
      dockerStrategy:
        {{- if $cval.Build.From }}
        from:
          kind: {{ $cval.Build.From.Kind | quote }}
          name: "{{ $cval.Build.From.Name }}:{{ default "latest" $cval.Build.From.Tag }}"
        {{- end }}
        {{- if $cval.Build.Env }}
        env:
        {{- range $ekey, $eval := $cval.Build.Env }}
        - name: {{ $ekey | quote }}
          value: {{ $eval | quote }}
        {{- end }}
        {{- end }}
        noCache: true
        forcePull: true
        {{- if $root.Values.Images.OS }}
        dockerfilePath: "Dockerfile.{{ $root.Values.Images.OS }}"
        {{- end }}
      type: Docker
    triggers: {{ if not $cval.Build.Triggers }}[]{{- else -}}
    {{- range $index, $trigger := $cval.Build.Triggers }}
    - type: {{ $trigger.Type | quote }}
      {{- if eq "ImageChange" $trigger.Type }}
      imageChange: {{ if not $trigger.From }}{}{{- else -}}
        from:
          kind: {{ $trigger.From.Kind | quote }}
          name: "{{ $trigger.From.Name }}:{{ default "latest" $trigger.From.Tag }}"
        {{- end -}}
      {{- end -}}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}