{{- if and (.Values.Agent.Enabled) -}}
apiVersion: v1
kind: List
items:
  {{- $root := . -}}
  {{- range $pkey, $pval := .Values.Agent.PodTemplates -}}
  {{- range $index, $cval := $pval.Containers -}}
  {{- if $cval.Build }}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        {{- include "jenkins-openshift.labels" $root | nindent 8 }}
        build: jenkins
      name: {{ regexSplit "/" $cval.Image -1 | last | quote }}
    spec: {}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}